Repository cloudposse/terraform-aws-components, pull requests merged in 2022-09, with the labels that each got.

#337 feat: Upstream `strongdm` component
  modules/strongdm/README.md
  modules/strongdm/charts/strongdm/.helmignore
  modules/strongdm/charts/strongdm/Chart.yaml
  modules/strongdm/charts/strongdm/templates/_helpers.tpl
  modules/strongdm/charts/strongdm/templates/configmap.yaml
  modules/strongdm/charts/strongdm/templates/daemonset.yaml
  modules/strongdm/charts/strongdm/templates/deployment.yaml
  modules/strongdm/charts/strongdm/templates/secret.yaml
  modules/strongdm/charts/strongdm/templates/service.yaml
  modules/strongdm/charts/strongdm/values.yaml
  modules/strongdm/context.tf
  modules/strongdm/helm.tf
  modules/strongdm/main.tf
  modules/strongdm/providers.tf
  modules/strongdm/templates/sdm-cleanup.sh
  modules/strongdm/templates/strongdm-cleanup.values.yaml.tpl
  modules/strongdm/variables.tf
  modules/strongdm/versions.tf
Labels: terraform/1.x

#481 `cognito` readme cleanup
  modules/cognito/README.md
Labels: patch

#485 Upstream and replace `github-actions-runner` with `eks/actions-runner-controller`
  .pre-commit-config.yaml
  deprecated/github-actions-runner/README.md
  deprecated/github-actions-runner/context.tf
  deprecated/github-actions-runner/default.auto.tfvars
  deprecated/github-actions-runner/iam.tf
  deprecated/github-actions-runner/kms.tf
  deprecated/github-actions-runner/main.tf
  deprecated/github-actions-runner/outputs.tf
  deprecated/github-actions-runner/providers.tf
  deprecated/github-actions-runner/remote-state.tf
  deprecated/github-actions-runner/runners/actions-runner-controller/values.yaml
  deprecated/github-actions-runner/runners/actions-runner/chart/.helmignore
  deprecated/github-actions-runner/runners/actions-runner/chart/Chart.yaml
  deprecated/github-actions-runner/runners/actions-runner/chart/templates/hra.yaml
  deprecated/github-actions-runner/runners/actions-runner/chart/templates/runnerdeployment.yaml
  deprecated/github-actions-runner/runners/runner/Dockerfile
  deprecated/github-actions-runner/runners/runner/Makefile
  deprecated/github-actions-runner/runners/runner/docker-config.json
  deprecated/github-actions-runner/variables.tf
  deprecated/github-actions-runner/versions.tf
  modules/eks/actions-runner-controller/README.md
  modules/eks/actions-runner-controller/charts/actions-runner/.helmignore
  modules/eks/actions-runner-controller/charts/actions-runner/Chart.yaml
  modules/eks/actions-runner-controller/charts/actions-runner/templates/horizontalrunnerautoscaler.yaml
  modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml
  modules/eks/actions-runner-controller/context.tf
  modules/eks/actions-runner-controller/main.tf
  modules/eks/actions-runner-controller/outputs.tf
  modules/eks/actions-runner-controller/provider-helm.tf
  modules/eks/actions-runner-controller/providers.tf
  modules/eks/actions-runner-controller/remote-state.tf
  modules/eks/actions-runner-controller/resources/values.yaml
  modules/eks/actions-runner-controller/variables.tf
  modules/eks/actions-runner-controller/versions.tf
Labels: terraform/1.x

#493 s3-bucket: allow usage without providing a value for `tenant`
  .pre-commit-config.yaml
  modules/s3-bucket/remote-state.tf
Labels: terraform/1.x

#492 upstream `echo-server` with alb group and logging
  modules/eks/echo-server/README.md
  modules/eks/echo-server/charts/echo-server/templates/ingress.yaml
  modules/eks/echo-server/charts/echo-server/values.yaml
  modules/eks/echo-server/main.tf
  modules/eks/echo-server/remote-state.tf
  modules/eks/echo-server/variables.tf
Labels: terraform/1.x

#495 Allow IAM users to assume team roles via an optional flag
  modules/account-map/modules/team-assume-role-policy/README.md
  modules/account-map/modules/team-assume-role-policy/main.tf
  modules/account-map/modules/team-assume-role-policy/variables.tf
Labels: minor

#496 Update cold-start components
  modules/account-map/README.md
  modules/account-map/account-info.tftmpl
  modules/account-map/default.auto.tfvars
  modules/account-map/main.tf
  modules/account-map/modules/iam-roles/main.tf
  modules/account-map/modules/iam-roles/outputs.tf
  modules/account-map/modules/roles-to-principals/main.tf
  modules/account-map/modules/roles-to-principals/outputs.tf
  modules/account-map/modules/team-assume-role-policy/README.md
  modules/account-map/modules/team-assume-role-policy/github-assume-role-policy.mixin.tf
  modules/account-map/modules/team-assume-role-policy/main.tf
  modules/account-map/outputs.tf
  modules/account-map/remote-state.tf
  modules/account-map/variables.tf
  modules/account-map/versions.tf
  modules/account-settings/README.md
  modules/account-settings/default.auto.tfvars
  modules/account-settings/versions.tf
  modules/account/README.md
  modules/account/default.auto.tfvars
  modules/account/main.tf
  modules/account/outputs.tf
  modules/account/versions.tf
  modules/aws-saml/README.md
  modules/aws-saml/default.auto.tfvars
  modules/aws-saml/versions.tf
  modules/aws-team-roles/README.md
  modules/aws-team-roles/default.auto.tfvars
  modules/aws-team-roles/iam-role-info.tftmpl
  modules/aws-team-roles/main.tf
  modules/aws-team-roles/outputs.tf
  modules/aws-team-roles/remote-state.tf
  modules/aws-teams/README.md
  modules/aws-teams/default.auto.tfvars
  modules/aws-teams/main.tf
  modules/aws-teams/outputs.tf
  modules/aws-teams/policy-team-role-access.tf
  modules/aws-teams/remote-state.tf
  modules/aws-teams/versions.tf
  modules/tfstate-backend/README.md
  modules/tfstate-backend/default.auto.tfvars
  modules/tfstate-backend/iam.tf
  modules/tfstate-backend/variables.tf
  modules/tfstate-backend/versions.tf
Labels: minor
