Repository cloudposse/terraform-aws-components, pull requests merged in 2022-10, with the labels that each got.

#502 GitHub OIDC, ECR
  .editorconfig
  .github/workflows/bats.yml
  mixins/github-actions-iam-policy/ecr/github-actions-iam-policy.tf
  mixins/github-actions-iam-role/README-github-action-iam-role.md
  mixins/github-actions-iam-role/github-actions-iam-role.mixin.tf
  modules/ecr/README.md
  modules/ecr/providers.tf
  modules/ecr/variables.tf
  modules/ecr/versions.tf
  modules/github-oidc-provider/README.md
  modules/github-oidc-provider/default.auto.tfvars
  modules/github-oidc-provider/get_thumbprint.sh
  modules/github-oidc-provider/main.tf
  modules/github-oidc-provider/versions.tf
  modules/vpc/README.md
  modules/vpc/providers.tf
Labels: minor

#507 Fix feature allowing IAM users to assume team roles
  .github/workflows/bats.yml
  modules/account-map/modules/team-assume-role-policy/README.md
  modules/account-map/modules/team-assume-role-policy/main.tf
  modules/account-map/modules/team-assume-role-policy/variables.tf
Labels: minor

#516 Upstream iam-service-linked-roles
  modules/iam-service-linked-roles/README.md
  modules/iam-service-linked-roles/context.tf
  modules/iam-service-linked-roles/main.tf
  modules/iam-service-linked-roles/outputs.tf
  modules/iam-service-linked-roles/providers.tf
  modules/iam-service-linked-roles/variables.tf
  modules/iam-service-linked-roles/versions.tf
Labels: terraform/1.x

#520 Upstream iam-role component
  modules/iam-role/README.md
  modules/iam-role/context.tf
  modules/iam-role/main.tf
  modules/iam-role/outputs.tf
  modules/iam-role/providers.tf
  modules/iam-role/variables.tf
  modules/iam-role/versions.tf
Labels: terraform/1.x

#521 Allow vpc-peering to peer v2 to v2
  modules/account-map/modules/iam-roles/outputs.tf
  modules/account-map/modules/iam-roles/variables.tf
  modules/vpc-peering/README.md
  modules/vpc-peering/default.auto.tfvars
  modules/vpc-peering/main.tf
  modules/vpc-peering/providers.tf
  modules/vpc-peering/remote-state.tf
  modules/vpc-peering/variables.tf
Labels: terraform/1.x, patch
