Repository cloudposse/terraform-aws-components, pull requests merged in 2023-08, with the labels that each got.

#793 [eks/karpenter] Script to update Karpenter CRDs
  modules/eks/karpenter/karpenter-crd-upgrade
Labels: no-release

#794 [eks/storage-class] Initial implementation
  modules/eks/storage-class/README.md
  modules/eks/storage-class/context.tf
  modules/eks/storage-class/main.tf
  modules/eks/storage-class/outputs.tf
  modules/eks/storage-class/provider-helm.tf
  modules/eks/storage-class/providers.tf
  modules/eks/storage-class/remote-state.tf
  modules/eks/storage-class/variables.tf
  modules/eks/storage-class/versions.tf
Labels: no-release

#795 [eks/cluster] Add support for BottleRocket and EFS add-on
  deprecated/eks/ebs-controller/README.md
  deprecated/eks/ebs-controller/context.tf
  deprecated/eks/ebs-controller/main.tf
  deprecated/eks/ebs-controller/outputs.tf
  deprecated/eks/ebs-controller/provider-helm.tf
  deprecated/eks/ebs-controller/providers.tf
  deprecated/eks/ebs-controller/remote-state.tf
  deprecated/eks/ebs-controller/variables.tf
  deprecated/eks/ebs-controller/versions.tf
  deprecated/eks/efs-controller/README.md
  deprecated/eks/efs-controller/context.tf
  deprecated/eks/efs-controller/main.tf
  deprecated/eks/efs-controller/outputs.tf
  deprecated/eks/efs-controller/provider-helm.tf
  deprecated/eks/efs-controller/providers.tf
  deprecated/eks/efs-controller/remote-state.tf
  deprecated/eks/efs-controller/resources/iam_policy_statements.yaml
  deprecated/eks/efs-controller/resources/values.yaml
  deprecated/eks/efs-controller/variables.tf
  deprecated/eks/efs-controller/versions.tf
  deprecated/eks/eks-without-spotinst/README.md
  deprecated/eks/eks-without-spotinst/context.tf
  deprecated/eks/eks-without-spotinst/default.auto.tfvars
  deprecated/eks/eks-without-spotinst/eks-node-groups.tf
  deprecated/eks/eks-without-spotinst/main.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_az/context.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_az/main.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_az/outputs.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_az/variables.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_region/context.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_region/main.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_region/outputs.tf
  deprecated/eks/eks-without-spotinst/modules/node_group_by_region/variables.tf
  deprecated/eks/eks-without-spotinst/outputs.tf
  deprecated/eks/eks-without-spotinst/providers.tf
  deprecated/eks/eks-without-spotinst/remote-state.tf
  deprecated/eks/eks-without-spotinst/variables.tf
  deprecated/eks/eks-without-spotinst/versions.tf
  modules/eks/cluster/CHANGELOG.md
  modules/eks/cluster/README.md
  modules/eks/cluster/addons.tf
  modules/eks/cluster/eks-node-groups.tf
  modules/eks/cluster/karpenter.tf
  modules/eks/cluster/main.tf
  modules/eks/cluster/modules/node_group_by_az/main.tf
  modules/eks/cluster/modules/node_group_by_az/variables.tf
  modules/eks/cluster/modules/node_group_by_region/variables.tf
  modules/eks/cluster/variables.tf
  modules/eks/cluster/versions.tf
  modules/eks/karpenter/README.md
  modules/eks/karpenter/main.tf
  modules/eks/karpenter/variables.tf
  modules/vpc/README.md
  modules/vpc/variables.tf
Labels: minor

#803 Updated Security Group Component to 2.2.0
  modules/bastion/README.md
  modules/bastion/main.tf
  modules/rds/README.md
  modules/rds/main.tf
  modules/redshift/README.md
  modules/redshift/main.tf
  modules/spacelift/worker-pool/README.md
  modules/spacelift/worker-pool/main.tf
  modules/vpc/README.md
  modules/vpc/main.tf
Labels: patch

#805 Added Enabled Parameter to aws-saml/okta-user and datadog-synthetics-private-location
  modules/aws-saml/modules/okta-user/main.tf
  modules/datadog-private-location-ecs/main.tf
Labels: patch

#806 [eks/cluster] Proper handling of cold start and enabled=false
  modules/eks/cluster/README.md
  modules/eks/cluster/addons.tf
  modules/eks/cluster/eks-node-groups.tf
  modules/eks/cluster/fargate-profiles.tf
  modules/eks/cluster/main.tf
  modules/eks/cluster/remote-state.tf
Labels: minor

#807 Update upgrade-guide.md Version
  docs/upgrade-guide.md
Labels: no-release

#813 Fix eks/cluster default values
  modules/eks/cluster/README.md
  modules/eks/cluster/variables.tf
Labels: patch

#816 Karpenter bugfix, EKS add-ons to mangaed node group
  modules/eks/cluster/README.md
  modules/eks/cluster/variables.tf
  modules/eks/karpenter/main.tf
Labels: bugfix

#817 Update storage-class efs component documentation
  modules/eks/storage-class/README.md
Labels: no-release

#814 Datadog upgrades
  modules/datadog-configuration/README.md
  modules/datadog-configuration/main.tf
  modules/datadog-configuration/modules/datadog_keys/README.md
  modules/datadog-configuration/modules/datadog_keys/providers.tf
  modules/datadog-configuration/ssm.tf
  modules/datadog-integration/CHANGELOG.md
  modules/datadog-integration/README.md
  modules/datadog-integration/main.tf
  modules/datadog-integration/variables.tf
  modules/datadog-lambda-forwarder/CHANGELOG.md
  modules/datadog-lambda-forwarder/README.md
  modules/datadog-lambda-forwarder/main.tf
  modules/datadog-lambda-forwarder/remote-state.tf
  modules/datadog-lambda-forwarder/variables.tf
  modules/datadog-monitor/CHANGELOG.md
  modules/datadog-monitor/README.md
  modules/datadog-monitor/main.tf
  modules/datadog-monitor/variables.tf
  modules/datadog-synthetics-private-location/CHANGELOG.md
  modules/datadog-synthetics-private-location/README.md
  modules/datadog-synthetics-private-location/main.tf
  modules/datadog-synthetics-private-location/outputs.tf
  modules/datadog-synthetics-private-location/remote-state.tf
  modules/datadog-synthetics/README.md
  modules/datadog-synthetics/remote-state.tf
  modules/eks/datadog-agent/CHANGELOG.md
  modules/eks/datadog-agent/README.md
  modules/eks/datadog-agent/main.tf
  modules/eks/datadog-agent/remote-state.tf
  modules/eks/datadog-agent/values.yaml
  modules/eks/datadog-agent/variables.tf
Labels: minor

#822 update boolean logic
  modules/guardduty/main.tf
Labels: patch

#821 [eks/alb-controller] Update ALB controller IAM policy
  modules/eks/alb-controller/CHANGELOG.md
  modules/eks/alb-controller/README.md
  modules/eks/alb-controller/distributed-iam-policy.tf
  modules/eks/alb-controller/main.tf
Labels: bugfix

#826 Fix naming convention of overridable local variable
  modules/eks/alb-controller/CHANGELOG.md
  modules/eks/alb-controller/distributed-iam-policy.tf
  modules/eks/alb-controller/main.tf
Labels: bugfix

#834 [spacelift/worker-pool] Update providers.tf nesting
  modules/spacelift/worker-pool/README.md
  modules/spacelift/worker-pool/providers.tf
Labels: bugfix

#827 GHA workflow to update Changelog
  .github/workflows/update-changelog.yml
  CHANGELOG.md
  docs/upgrade-guide.md
Labels: patch

#848 Update helm-release to v0.10.0
  modules/datadog-synthetics-private-location/README.md
  modules/datadog-synthetics-private-location/main.tf
  modules/eks/actions-runner-controller/README.md
  modules/eks/actions-runner-controller/main.tf
  modules/eks/alb-controller/README.md
  modules/eks/alb-controller/main.tf
  modules/eks/argocd/README.md
  modules/eks/argocd/main.tf
  modules/eks/aws-node-termination-handler/README.md
  modules/eks/aws-node-termination-handler/main.tf
  modules/eks/cert-manager/README.md
  modules/eks/cert-manager/main.tf
  modules/eks/datadog-agent/README.md
  modules/eks/datadog-agent/main.tf
  modules/eks/echo-server/README.md
  modules/eks/echo-server/main.tf
  modules/eks/external-dns/README.md
  modules/eks/external-dns/main.tf
  modules/eks/external-secrets-operator/README.md
  modules/eks/external-secrets-operator/main.tf
  modules/eks/idp-roles/README.md
  modules/eks/idp-roles/main.tf
  modules/eks/karpenter/README.md
  modules/eks/karpenter/main.tf
  modules/eks/keda/README.md
  modules/eks/keda/main.tf
  modules/eks/metrics-server/README.md
  modules/eks/metrics-server/main.tf
  modules/eks/redis-operator/README.md
  modules/eks/redis-operator/main.tf
  modules/eks/redis/README.md
  modules/eks/redis/main.tf
Labels: bugfix, minor
