Repository cloudposse/terraform-aws-components, pull requests merged in 2023-02, with the labels that each got.

#546 Fixed non-html tags that fails rendering on docusaurus
  README.md
  modules/datadog-agent/README.md
  modules/eks/external-dns/README.md
  modules/eks/external-dns/variables.tf
  modules/zscaler/README.md
Labels: patch

#567 SSO upgrades and Support for Assume Role from Identity Users
  modules/account-map/modules/roles-to-principals/main.tf
  modules/aws-sso/README.md
  modules/aws-sso/main.tf
  modules/aws-sso/outputs.tf
  modules/aws-sso/policy-AdminstratorAccess.tf
  modules/aws-sso/policy-BillingAdministratorAccess.tf
  modules/aws-sso/policy-BillingReadOnlyAccess.tf
  modules/aws-sso/policy-DNSAdministratorAccess.tf
  modules/aws-sso/policy-Identity-role-TeamAccess.tf
  modules/aws-sso/policy-PoweruserAccess.tf
  modules/aws-sso/policy-ReadOnlyAccess.tf
  modules/aws-sso/policy-TerraformUpdateAccess.tf
  modules/aws-sso/remote-state.tf
  modules/aws-sso/variables.tf
Labels: minor

#556 Add spacelift-policy component
  modules/spacelift-policy/README.md
  modules/spacelift-policy/context.tf
  modules/spacelift-policy/main.tf
  modules/spacelift-policy/outputs.tf
  modules/spacelift-policy/policies/example.trigger.administrative.rego
  modules/spacelift-policy/policies/plan.autodeployupdates.rego
  modules/spacelift-policy/providers.tf
  modules/spacelift-policy/variables.tf
  modules/spacelift-policy/versions.tf
Labels: terraform/1.x
