Repository cloudposse/terraform-aws-components, pull requests merged in 2023-07, with the labels that each got.

#740 bugfix `aws-sso`, `github-oidc-provider`
  modules/aws-sso/CHANGELOG.md
  modules/aws-sso/README.md
  modules/aws-sso/main.tf
  modules/aws-sso/policy-Identity-role-TeamAccess.tf
  modules/aws-sso/policy-TerraformUpdateAccess.tf
  modules/aws-sso/providers.tf
  modules/aws-sso/remote-state.tf
  modules/aws-sso/variables.tf
  modules/github-oidc-provider/providers.tf
Labels: patch, bugfix

#748 Restore backwards compatibility of account-map output
  modules/account-map/README.md
  modules/account-map/main.tf
  modules/account-map/outputs.tf
Labels: minor

#737 Use the new subnets data source
  modules/eks/eks-without-spotinst/modules/node_group_by_az/main.tf
Labels: patch

#758 Make alb-controller default Ingress actually the default Ingress
  modules/eks/alb-controller/main.tf
Labels: minor

#759 [eks/karpenter-provisioner] minor improvements
  modules/eks/karpenter-provisioner/README.md
  modules/eks/karpenter-provisioner/main.tf
  modules/eks/karpenter-provisioner/variables.tf
  modules/eks/karpenter/README.md
  modules/eks/karpenter/main.tf
Labels: patch

#761 [aws-teams] Remove obsolete restriction on assuming roles in identity account
  modules/aws-teams/policy-team-role-access.tf
Labels: patch, bugfix

#776 [vpc] bugfix, [aurora-postgres] & [cloudtrail-bucket] Tflint fixes
  modules/aurora-postgres/variables.tf
  modules/cloudtrail-bucket/README.md
  modules/cloudtrail-bucket/variables.tf
  modules/vpc/main.tf
Labels: patch, bugfix
