Repository cloudposse/terraform-aws-components, pull requests merged in 2024-07, with the labels that each got.

#1077 [eks/actions-runner-controller] Fix misconfigured document separators in Helm chart template
  modules/eks/actions-runner-controller/CHANGELOG.md
  modules/eks/actions-runner-controller/charts/actions-runner/Chart.yaml
  modules/eks/actions-runner-controller/charts/actions-runner/templates/runnerdeployment.yaml
  modules/eks/karpenter-node-pool/CHANGELOG.md
  modules/eks/karpenter/CHANGELOG.md
Labels: bugfix

#1080 feat: add additional variables and outputs for `spa-s3-cloudfront`
  modules/spa-s3-cloudfront/README.md
  modules/spa-s3-cloudfront/main.tf
  modules/spa-s3-cloudfront/outputs.tf
  modules/spa-s3-cloudfront/variables.tf
Labels: enhancement

#1083 Fix README Format
  modules/ec2-client-vpn/README.md
  modules/ecs-service/docs/ecs-partial-task-definitions.md
Labels: no-release

#1084 Fix: README Formatting for Docusarus
  modules/account/README.md
  modules/datadog-lambda-forwarder/README.md
  modules/datadog-lambda-forwarder/variables.tf
  modules/dns-primary/README.md
  modules/ecr/README.md
  modules/eks/actions-runner-controller/README.md
  modules/eks/datadog-agent/README.md
  modules/eks/github-actions-runner/README.md
  modules/github-runners/README.md
  modules/redshift/README.md
  modules/redshift/versions.tf
Labels: no-release
