Repository cloudposse/terraform-aws-components, pull requests merged in 2024-10, with the labels that each got.

#986 docs: improve external-dns snippet in readme
  modules/eks/external-dns/README.md
Labels: no-release

#985 feat: add support latest alb controller
  modules/eks/alb-controller/README.md
  modules/eks/alb-controller/distributed-iam-policy.tf
  modules/eks/alb-controller/main.tf
  modules/eks/alb-controller/remote-state.tf
  modules/eks/alb-controller/variables.tf
Labels: lgtm

#602 mq-broker: upgrade versions
  modules/mq-broker/README.md
  modules/mq-broker/context.tf
  modules/mq-broker/main.tf
  modules/mq-broker/outputs.tf
  modules/mq-broker/variables.tf
  modules/mq-broker/versions.tf
Labels: patch

#1151 feat: Configurable origin request policies for `spa-s3-cloudfront`
  modules/spa-s3-cloudfront/README.md
  modules/spa-s3-cloudfront/ordered_cache.tf
  modules/spa-s3-cloudfront/variables.tf
Labels: enhancement

#1156 fix: Frontmatter for `run-ons`
  modules/runs-on/README.md
Labels: no-release

#1166 fix: Runs-On README
  modules/runs-on/README.md
Labels: no-release

#1167 [dns-delegated] Fix README.md to remove suggestion of deploying regionally
  modules/dns-delegated/README.md
Labels: no-release, readme

#1170 feat(elasticache-redis): add engine input for valkey support
  modules/elasticache-redis/README.md
  modules/elasticache-redis/main.tf
  modules/elasticache-redis/modules/redis_cluster/main.tf
  modules/elasticache-redis/modules/redis_cluster/variables.tf
Labels: enhancement
